version: '3.8'
services:
  redis:
    image: redis
    container_name: web3mt_redis
    ports:
      - "6379:6379"
    volumes:
      - web3mt_redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: web3mt_redisinsight
    ports:
      - "5540:5540"
    volumes:
      - web3mt_redisinsight_data:/db
    depends_on:
      - redis

volumes:
  web3mt_redis_data:
  web3mt_redisinsight_data: